apiVersion: v1
kind: Service
metadata:
  name: {{ include "gdna-lyzr-baseline.fullname" . }}-backend
  labels:
    {{- include "gdna-lyzr-baseline.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gdna-lyzr-baseline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend